Repository uclahs-cds/package-BoutrosLab-plotting-general, pull requests merged in 2023-10, with the labels that each got.

#150 Trigger R CMD check with dispatch
  .github/workflows/r-lib-check.yaml
  NEWS
Labels: testing

#161 Deprecate test file
  DESCRIPTION
  NEWS
  tests/test_plotting_functions.R
Labels: testing

#166 Autofix broken Confluence links
  .github/pull_request_template.md
Labels: documentation

#165 Auto axis scaling
  DESCRIPTION
  NEWS
  R/auto.axis.R
  R/create.boxplot.R
  R/create.hexbinplot.R
  R/create.manhattanplot.R
  R/create.scatterplot.R
  man/auto.axis.Rd
  man/create.barplot.Rd
  man/create.boxplot.Rd
  man/create.hexbinplot.Rd
  man/create.manhattanplot.Rd
  man/create.scatterplot.Rd
  tests/testthat.R
  tests/testthat/test-auto.axis.R
  tests/testthat/test-plotting.functions.R
  vignettes/PlottingGuide.Rnw
  vignettes/PlottingGuide.pdf
Labels: documentation, enhancement
